---
openapi: 3.0.2
info:
  title: Statistics on Assistance Services
  version: 1.0.0
  description: Single Digital Gateway API for the Statistics on Assistance Services.
  x-logo:
    url: ""
servers:
  - url: https://collect.youreurope.ec.europa.eu/{version}
    variables:
      version:
        default: v1
paths:
  /statistics/assistance-services:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/assistanceServiceStats'
        required: true
      security:
        - apiKey: []
      responses:
        "200":
          description: OK
      description: Create a new dataset related to a given reference period, identified
        by a unique key provided, or update the data if it already exists

components:
  schemas:
    assistanceServiceStats:
      type: object
      required:
        - uniqueId
        - referencePeriod
        - transferDate
        - transferType
        - nbEntries
        - sources
      properties:
        uniqueId:
          description: Unique ID for feedback submission for a specific reference period collected from the Unique ID web API call.
          type: string
        referencePeriod:
          $ref: '#/components/schemas/referencePeriod'
        transferDate:
          description: Date Time when the web API is called. The format must complies with the RFC 3339 standard. E.g.:2020-12-31T23:59:59.00Z (full-dateTfull-timeZ)
          format: date-time
          type: string
        transferType:
          type: string
          enum:
            - API
            - Manual
        nbEntries:
          type: number
        sources:
          type: array
          items:
            $ref: '#/components/schemas/source'
    source:
      type: object
      required:
        - sourceUrl
        - statistics
      properties:
        sourceUrl:
          type: string
        statistics:
          $ref: '#/components/schemas/urlStatistics'
    urlStatistics:
      description: An object representing the statistical information for one particular
        source URL. Array of objects because same URL can have several combination
        of statistics depending on the values of the object attributes.
      type: array
      items:
        type: object
        required:
          - nbRequests
          - categoryOfUser
          - subjectMatter
          - situationOfUser
          - avgResponseTime
        properties:
          nbRequests:
            type: integer
          categoryOfUser:
            type: string
            enum: ["citizen", "business"]
          subjectMatter:
            type: string
          sub-subjectMatter:
            type: string
          situationOfUser:
            type: string
            enum: ["cross-border", "national"]
          avgResponseTime:
            description: average response time in days
            type: integer
    referencePeriod:
      type: object
      required:
        - startDate
        - endDate
      properties:
        startDate:
          description: Start date of the reference period. The format must complies with the RFC 3339 standard. E.g.:2020-12-31T23:59:59.00Z (full-dateTfull-timeZ)
          format: date-time
          type: string
        endDate:
          description: End date of the reference period. The format must complies with the RFC 3339 standard. E.g.:2020-12-31T23:59:59.00Z (full-dateTfull-timeZ)
          format: date-time
          type: string

  securitySchemes:
    apiKey:
      type: apiKey
      description: Api key provided to the member states by the SDG management
      name: x-api-key
      in: header
